#!/bin/sh

export PGM=op2_cpu_timer
export PGM_PATH=${HOME}/Dropbox/IC_DoC/3_IndividualProject/OP2/src/particles/oplus2_rose/tests/hertz
export DATADIR=${HOME}/Dropbox/IC_DoC/3_IndividualProject/OP2/src/particles/hertz_framework/data
export PART_M_DIR=${DATADIR}/partitions/metis
export HERTZ_RSLT_PATH=${PGM_PATH}/hertz-output
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${HOME}/Dropbox/IC_DoC/3_IndividualProject/OP2/src/particles/hertz_framework/common

if [ -z "${NUMITER}" ]; then
  NUMITER=1000
fi

if [ -z "${OUTPUT}" ]; then
  OUTPUT=op2.data
fi



: << '#_comment_out'
# Smart Partition Non Random
for i in 128; do
	for j in 10; do

  		if [ $j = 1 ]; then
			${PGM_PATH}/${PGM} ${DATADIR}/${j}000.step -n ${NUMITER} -p ${PART_M_DIR}/${j}000.metis.part.${i} -v;
		else
			${PGM_PATH}/${PGM} ${DATADIR}/${j}000.step -n ${NUMITER} -p ${PART_M_DIR}/${j}000.metis.part.${i}   ;
  		fi
	done
done
#_comment_out



# Smart Partition Non Random
for i in 128 256 384 512 640 768 896 1024 1280 1536 1792 2048 2304 2560 2816 3072 3328 3584 3840 4096; do

	for j in 1; do

  		if [ $j = 1 ]; then
			${PGM_PATH}/${PGM} ${DATADIR}/${j}000.step -n ${NUMITER} -p ${PART_M_DIR}/${j}000.metis.part.${i} -v;
		else
			${PGM_PATH}/${PGM} ${DATADIR}/${j}000.step -n ${NUMITER} -p ${PART_M_DIR}/${j}000.metis.part.${i}   ;
  		fi
	done
done




# Sequential Partition Non Random
for i in 128 256 384 512 640 768 896 1024 1280 1536 1792 2048 2304 2560 2816 3072 3328 3584 3840 4096; do

	for j in 1; do

  		if [ $j = 1 ]; then
			${PGM_PATH}/${PGM} ${DATADIR}/${j}000.step -n ${NUMITER} -b${i} -v;
		else
			${PGM_PATH}/${PGM} ${DATADIR}/${j}000.step -n ${NUMITER} -b${i}   ;
  		fi
	done
done


# Smart Partition Random
for i in 128 256 384 512 640 768 896 1024 1280 1536 1792 2048 2304 2560 2816 3072 3328 3584 3840 4096; do

	for j in 1; do

  		if [ $j = 1 ]; then
			${PGM_PATH}/${PGM} ${DATADIR}/${j}000.step -n ${NUMITER} -s 1 -p ${PART_M_DIR}/${j}000.metis.part.${i} -v;
		else
			${PGM_PATH}/${PGM} ${DATADIR}/${j}000.step -n ${NUMITER} -s 1 -p ${PART_M_DIR}/${j}000.metis.part.${i}   ;
  		fi
	done
done


# Sequential Partition Non Random
for i in 128 256 384 512 640 768 896 1024 1280 1536 1792 2048 2304 2560 2816 3072 3328 3584 3840 4096; do

	for j in 1; do

  		if [ $j = 1 ]; then
			${PGM_PATH}/${PGM} ${DATADIR}/${j}000.step -n ${NUMITER} -b${i} -s 1 -v;
		else
			${PGM_PATH}/${PGM} ${DATADIR}/${j}000.step -n ${NUMITER} -b${i} -s 1   ;
  		fi
	done
done




: << '#_comment_out'
#_comment_out


